// DO NOT EDIT. GENERATED BY ifaces

package print

// PrintIface handle printing
type PrintIface interface {
	// Level set level
	Level(lvl int)
	// Errorf print error
	Errorf(format string, a ...any)
	// Errorln print error
	Errorln(a ...any)
	// Warn print warning
	Warn(a ...any)
	// Warnf print warning
	Warnf(format string, a ...any)
}
