// Code generated by ifaces DO NOT EDIT.

package parser

// Method function receiver
type Method interface {
	// SetPkg set the package
	SetPkg(pkg string)
	// Line line number
	Line() int
	// TypeName typename
	TypeName() string
	// Name function name
	Name() string
	// Doc returns function documentation
	Doc() string
	// Signature return the function signature
	Signature() string
	// UsesTypeParams returns true if function declaration contains type parameters
	UsesTypeParams() bool
}
