// DO NOT EDIT. GENERATED BY ifaces

package generator

import (
	"bytes"
	"io"
)

// GeneratorIface interface generator
type GeneratorIface interface {
	// Generate generate interfaces source code for the gen sub command.
	Generate(srcs []*Src, current *bytes.Buffer, outfile string, output io.Writer) error
}
