// Code generated by ifaces DO NOT EDIT.

package generate

import (
	"bytes"
	"io"

	"github.com/dexterp/ifaces/internal/resources/source"
)

// GenerateIface interface generator
type GenerateIface interface {
	// Generate generate interfaces source code for the gen sub command.
	Generate(srcs []*source.Source, current *bytes.Buffer, outfile string, output io.Writer) error
}
